// Mock data for yield-bearing stablecoins
export interface YieldStable {
  id: string;
  name: string;
  symbol: string;
  protocol: string;
  chain: string;
  apy: number;
  tvl: number;
  collateralRatio: number;
  audited: boolean;
  change7d: number;
  change30d: number;
}

export const yieldStables: YieldStable[] = [
  {
    id: "1",
    name: "Aave USDC",
    symbol: "aUSDC",
    protocol: "Aave",
    chain: "Ethereum",
    apy: 4.52,
    tvl: 4200000000,
    collateralRatio: 1.0,
    audited: true,
    change7d: 0.12,
    change30d: -0.45,
  },
  {
    id: "2",
    name: "Compound USDC",
    symbol: "cUSDC",
    protocol: "Compound",
    chain: "Ethereum",
    apy: 4.38,
    tvl: 2800000000,
    collateralRatio: 1.0,
    audited: true,
    change7d: 0.08,
    change30d: -0.32,
  },
  {
    id: "3",
    name: "Curve 3Pool",
    symbol: "3Crv",
    protocol: "Curve",
    chain: "Ethereum",
    apy: 3.95,
    tvl: 3500000000,
    collateralRatio: 1.0,
    audited: true,
    change7d: -0.15,
    change30d: 0.22,
  },
  {
    id: "4",
    name: "Maker DSR",
    symbol: "sDAI",
    protocol: "MakerDAO",
    chain: "Ethereum",
    apy: 5.15,
    tvl: 1800000000,
    collateralRatio: 1.0,
    audited: true,
    change7d: 0.25,
    change30d: 0.18,
  },
  {
    id: "5",
    name: "Lido USDT",
    symbol: "stUSDT",
    protocol: "Lido",
    chain: "Ethereum",
    apy: 4.82,
    tvl: 1200000000,
    collateralRatio: 1.0,
    audited: true,
    change7d: 0.05,
    change30d: -0.12,
  },
  {
    id: "6",
    name: "Pendle PT-sUSDe",
    symbol: "PT-sUSDe",
    protocol: "Pendle",
    chain: "Ethereum",
    apy: 8.45,
    tvl: 890000000,
    collateralRatio: 0.95,
    audited: true,
    change7d: 0.42,
    change30d: 1.25,
  },
  {
    id: "7",
    name: "Ethena USDe",
    symbol: "USDe",
    protocol: "Ethena",
    chain: "Ethereum",
    apy: 12.8,
    tvl: 2400000000,
    collateralRatio: 1.02,
    audited: true,
    change7d: 0.85,
    change30d: 2.15,
  },
  {
    id: "8",
    name: "Mountain USDM",
    symbol: "USDM",
    protocol: "Mountain",
    chain: "Base",
    apy: 5.25,
    tvl: 450000000,
    collateralRatio: 1.0,
    audited: true,
    change7d: 0.18,
    change30d: 0.35,
  },
  {
    id: "9",
    name: "Aerodrome USD+",
    symbol: "USD+",
    protocol: "Aerodrome",
    chain: "Base",
    apy: 6.85,
    tvl: 320000000,
    collateralRatio: 1.0,
    audited: true,
    change7d: 0.28,
    change30d: 0.65,
  },
  {
    id: "10",
    name: "Morpho USDC",
    symbol: "mUSDC",
    protocol: "Morpho",
    chain: "Base",
    apy: 7.15,
    tvl: 580000000,
    collateralRatio: 1.0,
    audited: true,
    change7d: 0.35,
    change30d: 0.92,
  },
  {
    id: "11",
    name: "Spark DAI",
    symbol: "sDAI",
    protocol: "Spark",
    chain: "Ethereum",
    apy: 5.05,
    tvl: 950000000,
    collateralRatio: 1.0,
    audited: true,
    change7d: 0.15,
    change30d: 0.08,
  },
  {
    id: "12",
    name: "Flux USDC",
    symbol: "fUSDC",
    protocol: "Flux",
    chain: "Ethereum",
    apy: 4.95,
    tvl: 280000000,
    collateralRatio: 1.0,
    audited: true,
    change7d: 0.02,
    change30d: -0.18,
  },
  {
    id: "13",
    name: "Gearbox USDC",
    symbol: "dUSDC",
    protocol: "Gearbox",
    chain: "Ethereum",
    apy: 6.25,
    tvl: 420000000,
    collateralRatio: 0.98,
    audited: true,
    change7d: 0.22,
    change30d: 0.45,
  },
  {
    id: "14",
    name: "Instadapp USDC",
    symbol: "iUSDC",
    protocol: "Instadapp",
    chain: "Ethereum",
    apy: 5.85,
    tvl: 380000000,
    collateralRatio: 1.0,
    audited: true,
    change7d: 0.18,
    change30d: 0.28,
  },
  {
    id: "15",
    name: "Silo USDC",
    symbol: "sUSDC",
    protocol: "Silo",
    chain: "Ethereum",
    apy: 7.85,
    tvl: 180000000,
    collateralRatio: 0.95,
    audited: true,
    change7d: 0.45,
    change30d: 0.85,
  },
  {
    id: "16",
    name: "Radiant USDC",
    symbol: "rUSDC",
    protocol: "Radiant",
    chain: "Arbitrum",
    apy: 5.45,
    tvl: 220000000,
    collateralRatio: 1.0,
    audited: true,
    change7d: 0.12,
    change30d: 0.15,
  },
  {
    id: "17",
    name: "Venus USDT",
    symbol: "vUSDT",
    protocol: "Venus",
    chain: "BNB Chain",
    apy: 4.25,
    tvl: 680000000,
    collateralRatio: 1.0,
    audited: true,
    change7d: -0.08,
    change30d: -0.25,
  },
  {
    id: "18",
    name: "JustLend USDT",
    symbol: "jUSDT",
    protocol: "JustLend",
    chain: "Tron",
    apy: 4.15,
    tvl: 1200000000,
    collateralRatio: 1.0,
    audited: true,
    change7d: 0.05,
    change30d: 0.02,
  },
  {
    id: "19",
    name: "Solend USDC",
    symbol: "sUSDC",
    protocol: "Solend",
    chain: "Solana",
    apy: 5.95,
    tvl: 290000000,
    collateralRatio: 1.0,
    audited: true,
    change7d: 0.28,
    change30d: 0.55,
  },
  {
    id: "20",
    name: "Kamino USDC",
    symbol: "kUSDC",
    protocol: "Kamino",
    chain: "Solana",
    apy: 8.25,
    tvl: 340000000,
    collateralRatio: 0.98,
    audited: true,
    change7d: 0.52,
    change30d: 1.15,
  },
];

export const formatCurrency = (value: number): string => {
  if (value >= 1e9) return `$${(value / 1e9).toFixed(2)}B`;
  if (value >= 1e6) return `$${(value / 1e6).toFixed(2)}M`;
  if (value >= 1e3) return `$${(value / 1e3).toFixed(2)}K`;
  return `$${value.toFixed(2)}`;
};

export const formatPercentage = (value: number): string => {
  const sign = value >= 0 ? "+" : "";
  return `${sign}${value.toFixed(2)}%`;
};
